### ISSUE TITLE
Consider a different name

### ISSUE THREAD

**Issue by cassidyjames** [theCalcaholic/streamdeck#3] opened 2022-10-04 21:00 UTC
[Stream Deck](https://www.elgato.com/en/stream-deck) is already a thing; naming your app the same thing is really confusing. I saw "Stream Deck" was on Flathub and thought it was the Elgato software of the same name.

**Comment by theCalcaholic** [comment] 2022-10-04 21:40
Duplicate of #1

**Closed as completed** 2022-10-04 21:40 UTC
